---
language: c
sudo: false

env:
  - TARGET=test_xenial_java8
  - TARGET=test_bionic_java8
  - TARGET=test_focal_java8
  - TARGET=test_centos7_java8
  # Need some fixes for java 11 to work with the test suite
  #- TARGET=test_xenial_java11
  #- TARGET=test_bionic_java11
  #- TARGET=test_centos7_java11

services:
  - docker

script:
  - make $TARGET
