---
sudo: required

services:
  - docker

before_install:
  - docker build -f dockerfiles/Dockerfile.bionic . -t jolynch/jvmquake:test_bionic
  - docker build -f dockerfiles/Dockerfile.xenial . -t jolynch/jvmquake:test_xenial

script:
  - docker run jolynch/jvmquake:test_bionic && docker run jolynch/jvmquake:test_xenial

